version: 1
accounts:
- name: alice
  coins: ["100000000uatom, 100000000000000000000avince"]
- name: bob
  coins: ["5000000000000avince"]

validators:
- name: alice
  bonded: 100000000000000000000avince

faucet:
  name: bob
  coins: ["10avince"]
  
  host: 0.0.0.0:4500


build:
  binary: "vinced"

init:
  app:
    evm-rpc:
      address: "0.0.0.0:8545"
      ws-address: "0.0.0.0:8546"
  home: "$HOME/.vinced"


genesis:
  chain_id: "vince_1000-1"
  app_state:
    crisis:
      constant_fee:
        denom: "avince"
    evm:
      params:
        evm_denom: "avince"
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: "avince"
    mint:
      params:
        mint_denom: "avince"
    staking:
      params:
        bond_denom: "avince"



host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9092"
  grpc-web: ":9093"
  api: ":1318"